apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: argo-apps
spec:
  components:
    - name: apps
      type: kustomize
      properties:
        repoType: git
        url: https://github.com/Deepdelver/DeepDeploy
        secretRef: git-secret
        pullInterval: 1m
        git:

          ref: refs/heads/main
        path: ./argo



