apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: argo-apps
spec:
  components:
    - name: apps
      type: kustomize
      properties:
        repoType: git
        url: https://github.com/Deepdelver/DeepDeploy
        secretRef: git-secret
        pullInterval: 1m
        git:
          branch: main
        path: ./argo

---
apiVersion: v1
kind: Secret
metadata:
  name: git-secret
  # # namespace: argocd
  # labels:
  # argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Deepdelver/DeepsLab
  password: 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
  username: Deepdelver
