apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-app
  namespace: default
spec:
  components:
    - name: my-server
      type: webservice
      properties:
        image: ghcr.io/fogdong/test-fog:master-a6f6a7d8-1632648915 # {"$imagepolicy": "default:gitops"}
        port: 8088
        env:
          - name: MYSQL_HOST
            value: my-cluster-mysql.mysql.svc.cluster.local
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: ROOT_PASSWORD
      traits:
        - type: ingress
          properties:
            domain: testsvc.example.com
            http:
              /: 8088

  policies:
    - name: env-policy
      type: env-binding
      properties:
        envs:
          - name: prod
            placement:
              clusterSelector:
                name: cluster-prod
            selector:
              components:
                - my-server

  workflow:
    steps:
      # 部署到预发环境中
      - name: deploy-staging
        type: deploy2env
        properties:
          policy: env-policy
          env: prod