apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: mysql
  namespace: mysql
spec:
  components:
    - name: mysql-controller
      type: helm
      properties:
        repoType: helm
        url: https://presslabs.github.io/charts
        chart: mysql-operator
        version: "0.4.0"
    - name: secret
      type: raw
      properties:
        apiVersion: v1
        kind: Secret
        metadata:
          name: my-cluster-secret
        type: Opaque
        stringData:
          ROOT_PASSWORD: my-pass
    - name: mysql-cluster
      type: raw
      properties:
        apiVersion: mysql.presslabs.org/v1alpha1
        kind: MysqlCluster
        metadata:
          name: my-cluster
        spec:
          replicas: 1
          secretName: my-cluster-secret
